export const APP_ID = 'babelchat';

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'de', name: 'German' },
  { code: 'ru', name: 'Russian' },
  { code: 'pl', name: 'Polish' },
];

export const UI_STRINGS = {
  English: {
    appTitle: 'BabelChat',
    appSubtitle: 'Real-time multilingual group chat',
    joinRoom: 'Join Room',
    createRoom: 'Create Room',
    roomId: 'Room ID',
    roomIdPlaceholder: 'Enter room ID...',
    yourName: 'Your Name',
    yourNamePlaceholder: 'Enter your name...',
    password: 'Password',
    passwordPlaceholder: 'Enter room password...',
    language: 'Your Language',
    joining: 'Joining...',
    creating: 'Creating...',
    send: 'Send',
    sending: 'Sending...',
    leaveRoom: 'Leave Room',
    deleteRoom: 'Delete Room',
    participants: 'Participants',
    kick: 'Kick',
    kicking: 'Kicking...',
    confirmDelete: 'Delete this room?',
    deleteConfirmMessage: 'This will permanently delete all messages and remove all participants. This cannot be undone.',
    cancel: 'Cancel',
    delete: 'Delete',
    deleting: 'Deleting...',
    typeMessage: 'Type a message',
    translating: 'Translating...',
    translationUnavailable: 'Translation unavailable',
    originalText: 'Original',
    loadEarlier: 'Load earlier messages',
    loading: 'Loading...',
    errorJoining: 'Failed to join. Please check the room ID and password.',
    errorCreating: 'Failed to create room.',
    errorSending: 'Failed to send message.',
    errorKicking: 'Failed to kick participant.',
    errorDeleting: 'Failed to delete room.',
    wrongPassword: 'Incorrect password.',
    roomNotFound: 'Room not found.',
    youWereKicked: 'You have been removed from this room.',
    readOnlyHint: 'You are viewing this room — only the host can send messages.',
    joinedRoom: (name) => `${name} joined the room`,
    leftRoom: (name) => `${name} left the room`,
    kickedFrom: (kicked, kicker) => `${kicked} was removed by ${kicker}`,
  },

  German: {
    appTitle: 'BabelChat',
    appSubtitle: 'Mehrsprachiger Echtzeit-Gruppenchat',
    joinRoom: 'Raum beitreten',
    createRoom: 'Raum erstellen',
    roomId: 'Raum-ID',
    roomIdPlaceholder: 'Raum-ID eingeben...',
    yourName: 'Dein Name',
    yourNamePlaceholder: 'Namen eingeben...',
    password: 'Passwort',
    passwordPlaceholder: 'Passwort eingeben...',
    language: 'Deine Sprache',
    joining: 'Beitreten...',
    creating: 'Erstellen...',
    send: 'Senden',
    sending: 'Senden...',
    leaveRoom: 'Raum verlassen',
    deleteRoom: 'Raum löschen',
    participants: 'Teilnehmer',
    kick: 'Rauswerfen',
    kicking: 'Rauswerfen...',
    confirmDelete: 'Raum löschen?',
    deleteConfirmMessage: 'Dadurch werden alle Nachrichten und Teilnehmer dauerhaft gelöscht. Dies kann nicht rückgängig gemacht werden.',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    deleting: 'Löschen...',
    typeMessage: 'Nachricht eingeben',
    translating: 'Übersetzen...',
    translationUnavailable: 'Übersetzung nicht verfügbar',
    originalText: 'Original',
    loadEarlier: 'Ältere Nachrichten laden',
    loading: 'Laden...',
    errorJoining: 'Beitreten fehlgeschlagen. Bitte Raum-ID und Passwort prüfen.',
    errorCreating: 'Erstellen fehlgeschlagen.',
    errorSending: 'Nachricht konnte nicht gesendet werden.',
    errorKicking: 'Rauswerfen fehlgeschlagen.',
    errorDeleting: 'Raum konnte nicht gelöscht werden.',
    wrongPassword: 'Falsches Passwort.',
    roomNotFound: 'Raum nicht gefunden.',
    youWereKicked: 'Du wurdest aus dem Raum entfernt.',
    readOnlyHint: 'Du siehst nur zu — nur der Gastgeber kann Nachrichten senden.',
    joinedRoom: (name) => `${name} hat den Raum betreten`,
    leftRoom: (name) => `${name} hat den Raum verlassen`,
    kickedFrom: (kicked, kicker) => `${kicked} wurde von ${kicker} entfernt`,
  },

  Russian: {
    appTitle: 'BabelChat',
    appSubtitle: 'Многоязычный групповой чат в реальном времени',
    joinRoom: 'Войти в комнату',
    createRoom: 'Создать комнату',
    roomId: 'ID комнаты',
    roomIdPlaceholder: 'Введите ID комнаты...',
    yourName: 'Ваше имя',
    yourNamePlaceholder: 'Введите имя...',
    password: 'Пароль',
    passwordPlaceholder: 'Введите пароль...',
    language: 'Ваш язык',
    joining: 'Подключение...',
    creating: 'Создание...',
    send: 'Отправить',
    sending: 'Отправка...',
    leaveRoom: 'Покинуть комнату',
    deleteRoom: 'Удалить комнату',
    participants: 'Участники',
    kick: 'Исключить',
    kicking: 'Исключение...',
    confirmDelete: 'Удалить комнату?',
    deleteConfirmMessage: 'Все сообщения и участники будут удалены навсегда. Это действие нельзя отменить.',
    cancel: 'Отмена',
    delete: 'Удалить',
    deleting: 'Удаление...',
    typeMessage: 'Введите сообщение',
    translating: 'Перевод...',
    translationUnavailable: 'Перевод недоступен',
    originalText: 'Оригинал',
    loadEarlier: 'Загрузить старые сообщения',
    loading: 'Загрузка...',
    errorJoining: 'Не удалось войти. Проверьте ID и пароль комнаты.',
    errorCreating: 'Не удалось создать комнату.',
    errorSending: 'Не удалось отправить сообщение.',
    errorKicking: 'Не удалось исключить участника.',
    errorDeleting: 'Не удалось удалить комнату.',
    wrongPassword: 'Неверный пароль.',
    roomNotFound: 'Комната не найдена.',
    youWereKicked: 'Вы были удалены из комнаты.',
    readOnlyHint: 'Вы только читаете — только хозяин может отправлять сообщения.',
    joinedRoom: (name) => `${name} вошёл(а) в комнату`,
    leftRoom: (name) => `${name} покинул(а) комнату`,
    kickedFrom: (kicked, kicker) => `${kicked} был(а) исключён(а) пользователем ${kicker}`,
  },

  Polish: {
    appTitle: 'BabelChat',
    appSubtitle: 'Wielojęzyczny czat grupowy w czasie rzeczywistym',
    joinRoom: 'Dołącz do pokoju',
    createRoom: 'Utwórz pokój',
    roomId: 'ID pokoju',
    roomIdPlaceholder: 'Wpisz ID pokoju...',
    yourName: 'Twoje imię',
    yourNamePlaceholder: 'Wpisz imię...',
    password: 'Hasło',
    passwordPlaceholder: 'Wpisz hasło pokoju...',
    language: 'Twój język',
    joining: 'Łączenie...',
    creating: 'Tworzenie...',
    send: 'Wyślij',
    sending: 'Wysyłanie...',
    leaveRoom: 'Opuść pokój',
    deleteRoom: 'Usuń pokój',
    participants: 'Uczestnicy',
    kick: 'Wyrzuć',
    kicking: 'Wyrzucanie...',
    confirmDelete: 'Usunąć pokój?',
    deleteConfirmMessage: 'Wszystkie wiadomości i uczestnicy zostaną trwale usunięci. Tej operacji nie można cofnąć.',
    cancel: 'Anuluj',
    delete: 'Usuń',
    deleting: 'Usuwanie...',
    typeMessage: 'Wpisz wiadomość',
    translating: 'Tłumaczenie...',
    translationUnavailable: 'Tłumaczenie niedostępne',
    originalText: 'Oryginał',
    loadEarlier: 'Załaduj wcześniejsze wiadomości',
    loading: 'Ładowanie...',
    errorJoining: 'Nie udało się dołączyć. Sprawdź ID i hasło pokoju.',
    errorCreating: 'Nie udało się utworzyć pokoju.',
    errorSending: 'Nie udało się wysłać wiadomości.',
    errorKicking: 'Nie udało się wyrzucić uczestnika.',
    errorDeleting: 'Nie udało się usunąć pokoju.',
    wrongPassword: 'Nieprawidłowe hasło.',
    roomNotFound: 'Pokój nie został znaleziony.',
    youWereKicked: 'Zostałeś/aś usunięty/a z pokoju.',
    readOnlyHint: 'Tylko czytasz — tylko gospodarz może wysyłać wiadomości.',
    joinedRoom: (name) => `${name} dołączył(a) do pokoju`,
    leftRoom: (name) => `${name} opuścił(a) pokój`,
    kickedFrom: (kicked, kicker) => `${kicked} został(a) wyrzucony/a przez ${kicker}`,
  },
};

export function getT(language) {
  return UI_STRINGS[language] || UI_STRINGS.English;
}
