export const APP_ID = 'babelchat';

export const LANGUAGES = [
  { code: 'en', name: 'English',   nativeName: 'English',    flag: '🇬🇧' },
  { code: 'de', name: 'German',    nativeName: 'Deutsch',    flag: '🇩🇪' },
  { code: 'ru', name: 'Russian',   nativeName: 'Русский',    flag: '🇷🇺' },
  { code: 'pl', name: 'Polish',    nativeName: 'Polski',     flag: '🇵🇱' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', flag: '🇺🇦' },
];

export const UI_STRINGS = {
  English: {
    appTitle: 'BabelChat',
    appSubtitle: 'Real-time multilingual group chat',
    joinRoom: 'Join Room',
    createRoom: 'Create Room',
    roomId: 'Room ID',
    roomIdPlaceholder: 'Enter room ID...',
    yourName: 'Your Name',
    yourNamePlaceholder: 'Enter your name...',
    password: 'Password',
    passwordPlaceholder: 'Enter room password...',
    language: 'Your Language',
    joining: 'Joining...',
    creating: 'Creating...',
    send: 'Send',
    sending: 'Sending...',
    leaveRoom: 'Leave Room',
    deleteRoom: 'Delete Room',
    participants: 'Participants',
    kick: 'Kick',
    kicking: 'Kicking...',
    confirmDelete: 'Delete this room?',
    deleteConfirmMessage: 'This will permanently delete all messages and remove all participants. This cannot be undone.',
    cancel: 'Cancel',
    delete: 'Delete',
    deleting: 'Deleting...',
    typeMessage: 'Type a message',
    translating: 'Translating...',
    translationUnavailable: 'Translation unavailable',
    originalText: 'Original',
    loadEarlier: 'Load earlier messages',
    loading: 'Loading...',
    errorJoining: 'Failed to join. Please check the room ID and password.',
    errorCreating: 'Failed to create room.',
    errorSending: 'Failed to send message.',
    errorKicking: 'Failed to kick participant.',
    errorDeleting: 'Failed to delete room.',
    wrongPassword: 'Incorrect password.',
    roomNotFound: 'Room not found.',
    youWereKicked: 'You have been removed from this room.',
    myRooms: 'My Rooms',
    noMyRooms: 'No rooms created yet.',
    deleteAll: 'Delete All',
    rejoin: 'Rejoin',
    deleteAllConfirm: 'Delete all your rooms? This cannot be undone.',
    showOriginal: 'Show original',
    hideOriginal: 'Hide original',
    you: 'you',
    readOnlyHint: 'You are viewing this room — only the host can send messages.',
    joinedRoom: (name) => `${name} joined the room`,
    leftRoom: (name) => `${name} left the room`,
    kickedFrom: (kicked, kicker) => `${kicked} was removed by ${kicker}`,
  },

  German: {
    appTitle: 'BabelChat',
    appSubtitle: 'Mehrsprachiger Echtzeit-Gruppenchat',
    joinRoom: 'Raum beitreten',
    createRoom: 'Raum erstellen',
    roomId: 'Raum-ID',
    roomIdPlaceholder: 'Raum-ID eingeben...',
    yourName: 'Dein Name',
    yourNamePlaceholder: 'Namen eingeben...',
    password: 'Passwort',
    passwordPlaceholder: 'Passwort eingeben...',
    language: 'Deine Sprache',
    joining: 'Beitreten...',
    creating: 'Erstellen...',
    send: 'Senden',
    sending: 'Senden...',
    leaveRoom: 'Raum verlassen',
    deleteRoom: 'Raum löschen',
    participants: 'Teilnehmer',
    kick: 'Rauswerfen',
    kicking: 'Rauswerfen...',
    confirmDelete: 'Raum löschen?',
    deleteConfirmMessage: 'Dadurch werden alle Nachrichten und Teilnehmer dauerhaft gelöscht. Dies kann nicht rückgängig gemacht werden.',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    deleting: 'Löschen...',
    typeMessage: 'Nachricht eingeben',
    translating: 'Übersetzen...',
    translationUnavailable: 'Übersetzung nicht verfügbar',
    originalText: 'Original',
    loadEarlier: 'Ältere Nachrichten laden',
    loading: 'Laden...',
    errorJoining: 'Beitreten fehlgeschlagen. Bitte Raum-ID und Passwort prüfen.',
    errorCreating: 'Erstellen fehlgeschlagen.',
    errorSending: 'Nachricht konnte nicht gesendet werden.',
    errorKicking: 'Rauswerfen fehlgeschlagen.',
    errorDeleting: 'Raum konnte nicht gelöscht werden.',
    wrongPassword: 'Falsches Passwort.',
    roomNotFound: 'Raum nicht gefunden.',
    youWereKicked: 'Du wurdest aus dem Raum entfernt.',
    myRooms: 'Meine Räume',
    noMyRooms: 'Noch keine Räume erstellt.',
    deleteAll: 'Alle löschen',
    rejoin: 'Beitreten',
    deleteAllConfirm: 'Alle Räume löschen? Dies kann nicht rückgängig gemacht werden.',
    showOriginal: 'Original anzeigen',
    hideOriginal: 'Original verbergen',
    you: 'du',
    readOnlyHint: 'Du siehst nur zu — nur der Gastgeber kann Nachrichten senden.',
    joinedRoom: (name) => `${name} hat den Raum betreten`,
    leftRoom: (name) => `${name} hat den Raum verlassen`,
    kickedFrom: (kicked, kicker) => `${kicked} wurde von ${kicker} entfernt`,
  },

  Russian: {
    appTitle: 'BabelChat',
    appSubtitle: 'Многоязычный групповой чат в реальном времени',
    joinRoom: 'Войти в комнату',
    createRoom: 'Создать комнату',
    roomId: 'ID комнаты',
    roomIdPlaceholder: 'Введите ID комнаты...',
    yourName: 'Ваше имя',
    yourNamePlaceholder: 'Введите имя...',
    password: 'Пароль',
    passwordPlaceholder: 'Введите пароль...',
    language: 'Ваш язык',
    joining: 'Подключение...',
    creating: 'Создание...',
    send: 'Отправить',
    sending: 'Отправка...',
    leaveRoom: 'Покинуть комнату',
    deleteRoom: 'Удалить комнату',
    participants: 'Участники',
    kick: 'Исключить',
    kicking: 'Исключение...',
    confirmDelete: 'Удалить комнату?',
    deleteConfirmMessage: 'Все сообщения и участники будут удалены навсегда. Это действие нельзя отменить.',
    cancel: 'Отмена',
    delete: 'Удалить',
    deleting: 'Удаление...',
    typeMessage: 'Введите сообщение',
    translating: 'Перевод...',
    translationUnavailable: 'Перевод недоступен',
    originalText: 'Оригинал',
    loadEarlier: 'Загрузить старые сообщения',
    loading: 'Загрузка...',
    errorJoining: 'Не удалось войти. Проверьте ID и пароль комнаты.',
    errorCreating: 'Не удалось создать комнату.',
    errorSending: 'Не удалось отправить сообщение.',
    errorKicking: 'Не удалось исключить участника.',
    errorDeleting: 'Не удалось удалить комнату.',
    wrongPassword: 'Неверный пароль.',
    roomNotFound: 'Комната не найдена.',
    youWereKicked: 'Вы были удалены из комнаты.',
    myRooms: 'Мои комнаты',
    noMyRooms: 'Комнат пока нет.',
    deleteAll: 'Удалить все',
    rejoin: 'Войти',
    deleteAllConfirm: 'Удалить все комнаты? Это действие нельзя отменить.',
    showOriginal: 'Показать оригинал',
    hideOriginal: 'Скрыть оригинал',
    you: 'вы',
    readOnlyHint: 'Вы только читаете — только хозяин может отправлять сообщения.',
    joinedRoom: (name) => `${name} вошёл(а) в комнату`,
    leftRoom: (name) => `${name} покинул(а) комнату`,
    kickedFrom: (kicked, kicker) => `${kicked} был(а) исключён(а) пользователем ${kicker}`,
  },

  Polish: {
    appTitle: 'BabelChat',
    appSubtitle: 'Wielojęzyczny czat grupowy w czasie rzeczywistym',
    joinRoom: 'Dołącz do pokoju',
    createRoom: 'Utwórz pokój',
    roomId: 'ID pokoju',
    roomIdPlaceholder: 'Wpisz ID pokoju...',
    yourName: 'Twoje imię',
    yourNamePlaceholder: 'Wpisz imię...',
    password: 'Hasło',
    passwordPlaceholder: 'Wpisz hasło pokoju...',
    language: 'Twój język',
    joining: 'Łączenie...',
    creating: 'Tworzenie...',
    send: 'Wyślij',
    sending: 'Wysyłanie...',
    leaveRoom: 'Opuść pokój',
    deleteRoom: 'Usuń pokój',
    participants: 'Uczestnicy',
    kick: 'Wyrzuć',
    kicking: 'Wyrzucanie...',
    confirmDelete: 'Usunąć pokój?',
    deleteConfirmMessage: 'Wszystkie wiadomości i uczestnicy zostaną trwale usunięci. Tej operacji nie można cofnąć.',
    cancel: 'Anuluj',
    delete: 'Usuń',
    deleting: 'Usuwanie...',
    typeMessage: 'Wpisz wiadomość',
    translating: 'Tłumaczenie...',
    translationUnavailable: 'Tłumaczenie niedostępne',
    originalText: 'Oryginał',
    loadEarlier: 'Załaduj wcześniejsze wiadomości',
    loading: 'Ładowanie...',
    errorJoining: 'Nie udało się dołączyć. Sprawdź ID i hasło pokoju.',
    errorCreating: 'Nie udało się utworzyć pokoju.',
    errorSending: 'Nie udało się wysłać wiadomości.',
    errorKicking: 'Nie udało się wyrzucić uczestnika.',
    errorDeleting: 'Nie udało się usunąć pokoju.',
    wrongPassword: 'Nieprawidłowe hasło.',
    roomNotFound: 'Pokój nie został znaleziony.',
    youWereKicked: 'Zostałeś/aś usunięty/a z pokoju.',
    myRooms: 'Moje pokoje',
    noMyRooms: 'Brak utworzonych pokojów.',
    deleteAll: 'Usuń wszystkie',
    rejoin: 'Dołącz',
    deleteAllConfirm: 'Usunąć wszystkie pokoje? Tej operacji nie można cofnąć.',
    showOriginal: 'Pokaż oryginał',
    hideOriginal: 'Ukryj oryginał',
    you: 'ty',
    readOnlyHint: 'Tylko czytasz — tylko gospodarz może wysyłać wiadomości.',
    joinedRoom: (name) => `${name} dołączył(a) do pokoju`,
    leftRoom: (name) => `${name} opuścił(a) pokój`,
    kickedFrom: (kicked, kicker) => `${kicked} został(a) wyrzucony/a przez ${kicker}`,
  },
  Ukrainian: {
    appTitle: 'BabelChat',
    appSubtitle: 'Багатомовний груповий чат у реальному часі',
    joinRoom: 'Увійти до кімнати',
    createRoom: 'Створити кімнату',
    roomId: 'ID кімнати',
    roomIdPlaceholder: 'Введіть ID кімнати...',
    yourName: 'Ваше ім\'я',
    yourNamePlaceholder: 'Введіть ім\'я...',
    password: 'Пароль',
    passwordPlaceholder: 'Введіть пароль...',
    language: 'Ваша мова',
    joining: 'Підключення...',
    creating: 'Створення...',
    send: 'Надіслати',
    sending: 'Надсилання...',
    leaveRoom: 'Покинути кімнату',
    deleteRoom: 'Видалити кімнату',
    participants: 'Учасники',
    kick: 'Видалити',
    kicking: 'Видалення...',
    confirmDelete: 'Видалити кімнату?',
    deleteConfirmMessage: 'Усі повідомлення та учасники будуть видалені назавжди. Цю дію не можна скасувати.',
    cancel: 'Скасувати',
    delete: 'Видалити',
    deleting: 'Видалення...',
    typeMessage: 'Введіть повідомлення',
    translating: 'Переклад...',
    translationUnavailable: 'Переклад недоступний',
    originalText: 'Оригінал',
    loadEarlier: 'Завантажити старіші повідомлення',
    loading: 'Завантаження...',
    errorJoining: 'Не вдалося увійти. Перевірте ID і пароль кімнати.',
    errorCreating: 'Не вдалося створити кімнату.',
    errorSending: 'Не вдалося надіслати повідомлення.',
    errorKicking: 'Не вдалося видалити учасника.',
    errorDeleting: 'Не вдалося видалити кімнату.',
    wrongPassword: 'Невірний пароль.',
    roomNotFound: 'Кімнату не знайдено.',
    youWereKicked: 'Вас було видалено з кімнати.',
    myRooms: 'Мої кімнати',
    noMyRooms: 'Кімнат поки немає.',
    deleteAll: 'Видалити всі',
    rejoin: 'Увійти',
    deleteAllConfirm: 'Видалити всі кімнати? Цю дію не можна скасувати.',
    showOriginal: 'Показати оригінал',
    hideOriginal: 'Сховати оригінал',
    you: 'ви',
    readOnlyHint: 'Ви лише читаєте — тільки господар може надсилати повідомлення.',
    joinedRoom: (name) => `${name} увійшов(ла) до кімнати`,
    leftRoom: (name) => `${name} покинув(ла) кімнату`,
    kickedFrom: (kicked, kicker) => `${kicked} був(ла) видалений(а) користувачем ${kicker}`,
  },
};

export function getT(language) {
  return UI_STRINGS[language] || UI_STRINGS.English;
}
