export const APP_ID = 'babelchat';

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Spanish' },
  { code: 'fr', name: 'French' },
  { code: 'de', name: 'German' },
  { code: 'pl', name: 'Polish' },
  { code: 'it', name: 'Italian' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ru', name: 'Russian' },
  { code: 'zh', name: 'Chinese' },
  { code: 'ja', name: 'Japanese' },
  { code: 'ko', name: 'Korean' },
  { code: 'ar', name: 'Arabic' },
];

export const UI_STRINGS = {
  appTitle: 'BabelChat',
  appSubtitle: 'Real-time multilingual group chat',
  joinRoom: 'Join Room',
  createRoom: 'Create Room',
  roomId: 'Room ID',
  roomIdPlaceholder: 'Enter room ID...',
  yourName: 'Your Name',
  yourNamePlaceholder: 'Enter your name...',
  password: 'Password',
  passwordPlaceholder: 'Enter room password...',
  language: 'Your Language',
  joining: 'Joining...',
  creating: 'Creating...',
  send: 'Send',
  sending: 'Sending...',
  leaveRoom: 'Leave Room',
  deleteRoom: 'Delete Room',
  participants: 'Participants',
  showParticipants: 'Show Participants',
  kick: 'Kick',
  kicking: 'Kicking...',
  confirmDelete: 'Confirm Delete',
  deleteConfirmMessage: 'Are you sure you want to delete this room? This action cannot be undone.',
  cancel: 'Cancel',
  delete: 'Delete',
  deleting: 'Deleting...',
  typeMessage: 'Type a message...',
  translating: 'Translating...',
  translationUnavailable: 'Translation unavailable',
  originalText: 'Original',
  loadEarlier: 'Load earlier messages',
  loading: 'Loading...',
  errorJoining: 'Failed to join room. Please check the room ID and password.',
  errorCreating: 'Failed to create room.',
  errorSending: 'Failed to send message.',
  errorKicking: 'Failed to kick participant.',
  errorDeleting: 'Failed to delete room.',
  wrongPassword: 'Incorrect password.',
  roomNotFound: 'Room not found.',
  youWereKicked: 'You have been removed from this room.',
  joinedRoom: (name) => `${name} joined the room`,
  leftRoom: (name) => `${name} left the room`,
  kickedFrom: (kicked, kicker) => `${kicked} was removed by ${kicker}`,
};
